spring.application.name=warframe

spring.profiles.active=dev

api-prefix=/api

# Warframe Index properties
warframe.index.language=en
warframe.index.url=https://origin.warframe.com/PublicExport/index_${warframe.index.language}.txt.lzma
warframe.index.file.name=index_${warframe.index.language}.txt.lzma
warframe.index.file.path=warframe/src/main/resources/index/

# Warframe Profile id
warframe.profile.id=PLACEHOLDER
warframe.profile.url=http://content.warframe.com/dynamic/getProfileViewingData.php?playerId=

# Warframe Dynamic
warframe.dynamic.worldstate=https://api.warframestat.us/pc/?language=en
warframe.dynamic.alerts=https://content.warframe.com/dynamic/rss.php

# Warframe Public Export plus 
warframe.public.export.plus.url=https://browse.wf/warframe-public-export-plus/