server.port=8080
allowed-origins=http://localhost:4200

spring.threads.virtual.enabled=true
spring.datasource.url=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect