server.port=${PORT}
allowed-origins=${ALLOWED_ORIGIN}

spring.datasource.url=${JDBC_URI}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect